name: GoFile Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

# Same workflow already running නම් cancel කරනවා
concurrency:
  group: gofile-bot
  cancel-in-progress: true

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Write session file
        run: echo "${{ secrets.SESSION_FILE }}" | base64 -d > user_session.session

      - name: Run Bot
        env:
          TG_API_ID: ${{ secrets.TG_API_ID }}
          TG_API_HASH: ${{ secrets.TG_API_HASH }}
          TG_PHONE: ${{ secrets.TG_PHONE }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          OWNER_ID: ${{ secrets.OWNER_ID }}
          STRING_SESSION: ${{ secrets.STRING_SESSION }}
        run: python bot.py
